# Python Temelleri - Veri Bilimi İçin Programlama

## 1. Ekrana Yazdırma ve Yorum Satırları

- **`print()` Fonksiyonu**: Parantez içine verilen değeri (metin, sayı vb.) ekrana basar. Metinler (string'ler) çift tırnak `""` veya tek tırnak `''` içinde yazılır.
- **Yorum Satırları (`#`)**: `#` ile başlayan satırlar Python tarafından işlenmez. Kodun okunabilirliğini artırmak veya geçici olarak kod parçalarını devre dışı bırakmak için kullanılır.

In [ ]:
# Ekrana yazdırma örneği
print("Merhaba Dünya")

# Bu bir yorum satırıdır, çalıştırılmaz.
# print("Bu satır çalışmayacak")

Merhaba Dünya


## 2. Değişkenler ve Veri Tipleri

- **Değişkenler**: Verileri saklamak için kullanılan isimlendirilmiş alanlardır. Değer atamak için `=` operatörü kullanılır.
- **Değişken İsimlendirme Kuralları**:
  - Sayı ile başlayamaz.
  - Boşluk veya özel karakterler (`@`, `!`, `%` vb.) içeremez (alt çizgi `_` hariç).
  - Python anahtar kelimeleri (`if`, `else`, `while`, `for`, `def`, `class` vb.) olamaz.
- **Temel Veri Tipleri**:
  - `int`: Tam sayılar (örn: `5`, `-10`).
  - `float`: Ondalıklı sayılar (örn: `6.2`, `3.14`).
  - `str`: Metinler/Karakter dizileri (örn: `"Yasasin"`, `'Python'`).
  - `list`: Sıralı ve değiştirilebilir eleman koleksiyonu (örn: `[1, 2, 3]`, `['a', 5, 3.1]`)).
  - `bool`: Mantıksal değerler (`True` veya `False`).
- **`type()` Fonksiyonu**: Bir değişkenin veya değerin veri tipini öğrenmek için kullanılır.

In [ ]:
# Değişken tanımlama örnekleri
x = 5
y = 6.2
z = "Yasasin"
k = [1, 2, 3]
m = [[1, 2, 3], [1, 3, 4]] # İç içe liste
aktif = True

print("x değişkeninin değeri:", x)
print("y değişkeninin değeri:", y)
print("z değişkeninin değeri:", z)
print("k değişkeninin değeri:", k)
print("m değişkeninin değeri:", m)
print("aktif değişkeninin değeri:", aktif)

# Hatalı değişken tanımlamaları (yorum içinde bırakıldı)
# while = 4 # 'while' anahtar kelime olduğu için hata verir
# za@ = 9   # '@' özel karakter içerdiği için hata verir
# 2x = 34   # Sayı ile başladığı için hata verir

# Değişken tiplerini kontrol etme
print("x'in tipi:", type(x))
print("y'nin tipi:", type(y))
print("z'nin tipi:", type(z))
print("k'nın tipi:", type(k))
print("aktif'in tipi:", type(aktif))

x değişkeninin değeri: 5
y değişkeninin değeri: 6.2
z değişkeninin değeri: Yasasin
k değişkeninin değeri: [1, 2, 3]
m değişkeninin değeri: [[1, 2, 3], [1, 3, 4]]
aktif değişkeninin değeri: True
x'in tipi: <class 'int'>
y'nin tipi: <class 'float'>
z'nin tipi: <class 'str'>
k'nın tipi: <class 'list'>
aktif'in tipi: <class 'bool'>


## 3. Operatörler

### 3.1. Aritmetik Operatörler
- `+`: Toplama (sayılar için), Birleştirme (string'ler için).
- `-`: Çıkarma.
- `*`: Çarpma (sayılar için), Tekrarlama (string'ler için).
- `/`: Bölme (sonuç her zaman `float` olur).
- `**`: Üs alma.
- `%`: Modül alma (bölümden kalan).

In [ ]:
# Aritmetik operatör örnekleri
sayi1 = 10
sayi2 = 3
metin1 = "Merhaba"
metin2 = " Dünya"

print(f"{sayi1} + {sayi2} =", sayi1 + sayi2)
print(f"{sayi1} - {sayi2} =", sayi1 - sayi2)
print(f"{sayi1} * {sayi2} =", sayi1 * sayi2)
print(f"{sayi1} / {sayi2} =", sayi1 / sayi2)
print(f"{sayi1} ** {sayi2} =", sayi1 ** sayi2)
print(f"{sayi1} % {sayi2} =", sayi1 % sayi2)

print(metin1 + metin2)
print(metin1 * 3)

10 + 3 = 13
10 - 3 = 7
10 * 3 = 30
10 / 3 = 3.3333333333333335
10 ** 3 = 1000
10 % 3 = 1
Merhaba Dünya
MerhabaMerhabaMerhaba


### 3.2. Tip Dönüşüm Fonksiyonları
- `int()`: Başka bir tipi tam sayıya dönüştürür (ondalıklı kısmı atar).
- `float()`: Başka bir tipi ondalıklı sayıya dönüştürür.
- `str()`: Başka bir tipi metne (string) dönüştürür.

In [ ]:
# Tip dönüşümü örnekleri
ondalikli = 5.8
tam_sayi = 10
metin_sayi = "123"

print(f"{ondalikli} sayısının int() ile dönüşümü:", int(ondalikli))
print(f"{tam_sayi} sayısının float() ile dönüşümü:", float(tam_sayi))
print(f"{tam_sayi} sayısının str() ile dönüşümü:", str(tam_sayi))
print(f"{metin_sayi} metninin int() ile dönüşümü:", int(metin_sayi))

# String ile sayıyı birleştirmek için dönüşüm gerekir
print("Yaşım: " + str(30)) # Doğru kullanım
# print("Yaşım: " + 30) # Hata verir

5.8 sayısının int() ile dönüşümü: 5
10 sayısının float() ile dönüşümü: 10.0
10 sayısının str() ile dönüşümü: 10
123 metninin int() ile dönüşümü: 123
Yaşım: 30


### 3.3. Karşılaştırma Operatörleri
- `==`: Eşit mi?
- `!=`: Eşit değil mi?
- `>`: Büyük mü?
- `<`: Küçük mü?
- `>=`: Büyük veya eşit mi?
- `<=`: Küçük veya eşit mi?
Sonuçları `True` veya `False` (boolean) döner.

In [ ]:
# Karşılaştırma operatörleri örnekleri
a = 5
b = 10
c = 5

print(f"{a} == {b}:", a == b)
print(f"{a} == {c}:", a == c)
print(f"{a} != {b}:", a != b)
print(f"{a} > {b}:", a > b)
print(f"{a} < {b}:", a < b)
print(f"{b} >= {c}:", b >= c)
print(f"{a} <= {c}:", a <= c)

5 == 10: False
5 == 5: True
5 != 10: True
5 > 10: False
5 < 10: True
10 >= 5: True
5 <= 5: True


### 3.4. Mantıksal Operatörler
- `and` (`&`): Her iki koşul da `True` ise `True` döner.
- `or` (`|`): Koşullardan en az biri `True` ise `True` döner.
- `not`: Koşulun boolean değerini tersine çevirir (`True` ise `False`, `False` ise `True`).

In [ ]:
# Mantıksal operatör örnekleri
yas = 25
mezun = True

print("Yaş 18'den büyük MÜ ve mezun MU?", (yas > 18) and (mezun == True))
print("Yaş 18'den büyük MÜ veya mezun MU?", (yas > 18) or (mezun == False))
print("Mezun DEĞİL mi?", not mezun)

Yaş 18'den büyük MÜ ve mezun MU? True
Yaş 18'den büyük MÜ veya mezun MU? True
Mezun DEĞİL mi? False


## 4. Kütüphaneler ve `import`

- Python'un temel fonksiyonları dışında daha fazla işlevsellik için kütüphaneler kullanılır.
- `import kütüphane_adı`: Kütüphaneyi içe aktarır. Fonksiyonlarına `kütüphane_adı.fonksiyon()` şeklinde erişilir.
- `import kütüphane_adı as kısaltma`: Kütüphaneyi bir kısaltma ile içe aktarır. `kısaltma.fonksiyon()` şeklinde kullanılır (Örn: `import math as m`).
- `from kütüphane_adı import fonksiyon1, fonksiyon2`: Sadece belirtilen fonksiyonları içe aktarır. Direkt `fonksiyon1()` şeklinde kullanılır.
- `from kütüphane_adı import *`: Kütüphanedeki her şeyi içe aktarır (Genellikle önerilmez).

In [ ]:
# Matematik kütüphanesini 'm' kısaltmasıyla import etme
import math as m

print("Pi sayısı:", m.pi)
print("64'ün karekökü:", m.sqrt(64))
print("100'ün 10 tabanında logaritması:", m.log10(100))

# Sadece belirli fonksiyonları import etme
from math import pow, ceil

print("2'nin 5. kuvveti:", pow(2, 5))
print("4.3'ün yukarı yuvarlanmış hali:", ceil(4.3))

Pi sayısı: 3.141592653589793
64'ün karekökü: 8.0
100'ün 10 tabanında logaritması: 2.0
2'nin 5. kuvveti: 32.0
4.3'ün yukarı yuvarlanmış hali: 5


## 5. Fonksiyon Tanımlama (`def`)

- Belirli bir işi yapan veya tekrar kullanılacak kod bloklarını tanımlamak için kullanılır.
- `def fonksiyon_adı(parametre1, parametre2, ...):` şeklinde başlar.
- Fonksiyon içindeki kodlar girintili (indentation) yazılır.
- `parametre`'ler fonksiyonun dışarıdan alacağı girdilerdir.
- `return deger`: Fonksiyonun çalışması sonucunda bir değer döndürmesini sağlar. `return` yoksa fonksiyon `None` döndürür.
- **Lokal Değişkenler**: Fonksiyon içinde tanımlanan değişkenler sadece o fonksiyonun içinde geçerlidir.

In [ ]:
# Parametre alan ve değer döndüren fonksiyon
def ortalamabul(vize, final):
    # Fonksiyon içindeki 'ort' değişkeni lokaldir.
    ort = (vize * 0.4) + (final * 0.6)
    return ort

# Parametre alan ama değer döndürmeyen (None döndüren) fonksiyon
def selamla(isim):
    # Fonksiyon içindeki 'mesaj' değişkeni lokaldir.
    mesaj = "Merhaba, " + isim + "!"
    print(mesaj)

# Fonksiyonları çağırma
ogrenci_ortalamasi = ortalamabul(70, 90)
print("Öğrencinin ortalaması:", ogrenci_ortalamasi)

selamla("Ayşe")

# Lokal değişkene dışarıdan erişmeye çalışmak hata verir
# print(ort) # Hata! 'ort' sadece ortalamabul fonksiyonu içinde tanımlı.
# print(mesaj) # Hata! 'mesaj' sadece selamla fonksiyonu içinde tanımlı.

Öğrencinin ortalaması: 82.0
Merhaba, Ayşe!


## 6. Koşul Yapıları (`if`, `elif`, `else`)

- Belirli bir koşulun doğru (`True`) veya yanlış (`False`) olmasına göre farklı kod bloklarının çalıştırılmasını sağlar.
- `if kosul:`: Koşul doğruysa bu blok çalışır.
- `elif baska_kosul:`: Önceki `if` veya `elif` yanlışsa ve `baska_kosul` doğruysa bu blok çalışır. Birden fazla `elif` olabilir.
- `else:`: Yukarıdaki koşulların hiçbiri doğru değilse bu blok çalışır.

In [ ]:
def harf_notu_bul(ortalama):
    if ortalama >= 90:
        return "AA"
    elif ortalama >= 80:
        return "BA"
    elif ortalama >= 70:
        return "BB"
    elif ortalama >= 60:
        return "CB"
    elif ortalama >= 50:
        return "CC"
    else:
        return "FF (Kaldı)"

ort1 = ortalamabul(70, 90) # Önceki fonksiyondan 82.0 gelecek
ort2 = ortalamabul(40, 45) # Önceki fonksiyondan 43.0 gelecek

print(f"Ortalama {ort1} için harf notu: {harf_notu_bul(ort1)}")
print(f"Ortalama {ort2} için harf notu: {harf_notu_bul(ort2)}")

Ortalama 82.0 için harf notu: BA
Ortalama 43.0 için harf notu: FF (Kaldı)


## 7. Döngüler (`while`, `for`)

### 7.1. `while` Döngüsü
- Belirtilen koşul `True` olduğu sürece içindeki kod bloğunu tekrar tekrar çalıştırır.
- Koşulun döngü içinde değişerek bir noktada `False` olması gerekir, yoksa sonsuz döngü oluşur.
- `break`: Döngüyü anında sonlandırır.
- `continue`: Döngünün o anki adımını atlayıp bir sonraki adıma geçer.

In [ ]:
# 0'dan 5'e kadar (5 dahil) sayıları yazdıran while döngüsü
x = 0
print("While döngüsü başlangıcı:")
while x <= 5:
    print(x)
    x = x + 1 # Koşulu değiştiren güncelleme
print("While döngüsü bitti.")

# break kullanımı örneği
y = 15
print("\nBreak'li while döngüsü başlangıcı:")
while y > 5:
    print(y)
    y = y - 1
    if y == 9:
        print("y=9 oldu, break ile çıkılıyor.")
        break
print("Break'li while döngüsü bitti.")

While döngüsü başlangıcı:
0
1
2
3
4
5
While döngüsü bitti.

Break'li while döngüsü başlangıcı:
15
14
13
12
11
10
y=9 oldu, break ile çıkılıyor.
Break'li while döngüsü bitti.


### 7.2. `for` Döngüsü
- Bir dizi (string, liste, tuple vb.) veya yinelenebilir (iterable) bir nesnenin elemanları üzerinde gezinmek için kullanılır.
- `range(stop)`: 0'dan `stop-1`'e kadar sayılar üretir.
- `range(start, stop)`: `start`'tan `stop-1`'e kadar sayılar üretir.
- `range(start, stop, step)`: `start`'tan `stop-1`'e kadar `step` adım aralıklarla sayılar üretir.

In [ ]:
# String üzerinde for döngüsü
meyve = "elma"
print("\nString üzerinde for döngüsü:")
for harf in meyve:
    print(harf)

# range() ile for döngüsü
print("\nrange(5) ile for döngüsü:")
for i in range(5):
    print(i)

print("\nrange(2, 6) ile for döngüsü:")
for i in range(2, 6):
    print(i)

print("\nrange(1, 10, 2) ile for döngüsü:")
for i in range(1, 10, 2):
    print(i)

# Liste üzerinde for döngüsü
sayilar = [10, 20, 30]
print("\nListe üzerinde for döngüsü:")
for sayi in sayilar:
    print(sayi * 2)


String üzerinde for döngüsü:
e
l
m
a

range(5) ile for döngüsü:
0
1
2
3
4

range(2, 6) ile for döngüsü:
2
3
4
5

range(1, 10, 2) ile for döngüsü:
1
3
5
7
9

Liste üzerinde for döngüsü:
20
40
60


## 8. String (Metin) İşlemleri

- **İndeksleme**: `metin[index]`. İlk eleman `0`, son eleman `-1`.
- **Dilimleme (Slicing)**: `metin[start:stop:step]`. `start` dahil, `stop` hariç.
- **Uzunluk (`len`)**: `len(metin)` karakter sayısını verir.
- **Değiştirilemezlik (Immutability)**: String'in tek bir karakteri doğrudan değiştirilemez.
- **Metotlar**:

In [ ]:
z = "Python ile kodlamayı çok seviyorum"

# İndeksleme
print("İlk karakter:", z[0])
print("Son karakter:", z[-1])

# Dilimleme
print("1'den 12'ye (hariç) kadar:", z[1:12])
print("13'ten sona kadar:", z[13:])
print("Baştan 6'ya (hariç) kadar:", z[:6])

# Uzunluk
print("Metin uzunluğu:", len(z))

# Değiştirilemezlik (Hata verir - yorumda bırakıldı)
# z[0] = 'J' # TypeError: 'str' object does not support item assignment

# String Metotları
kucuk_z = "PYTHON"
print(f"{kucuk_z}.lower() ->", kucuk_z.lower())
print(f"{z}.upper() ->", z.upper())
print(f"z içinde 'o' harfi sayısı: {z.count('o')}")

# split: Metni boşluklara göre ayırır ve liste döndürür
kelimeler = z.split()
print(f"z.split() -> {kelimeler}")

# join: Liste elemanlarını araya belirtilen karakteri koyarak birleştirir
liste = ['çok', 'yorulduk', 'bitirelim']
birlesik = "-".join(liste)
print(f"'-'.join({liste}) -> {birlesik}")

İlk karakter: P
Son karakter: m
1'den 12'ye (hariç) kadar: ython ile k
13'ten sona kadar: dlamayı çok seviyorum
Baştan 6'ya (hariç) kadar: Python
Metin uzunluğu: 34
PYTHON.lower() -> python
Python ile kodlamayı çok seviyorum.upper() -> PYTHON ILE KODLAMAYI ÇOK SEVIYORUM
z içinde 'o' harfi sayısı: 4
z.split() -> ['Python', 'ile', 'kodlamayı', 'çok', 'seviyorum']
'-'.join(['çok', 'yorulduk', 'bitirelim']) -> çok-yorulduk-bitirelim


## 9. Listeler (Lists)

- Sıralı ve **değiştirilebilir** (mutable) eleman koleksiyonlarıdır.
- Köşeli parantez `[]` ile tanımlanır.
- Farklı veri tiplerini bir arada tutabilir.
- **İndeksleme ve Dilimleme**: String'ler gibidir.
- **Operatörler**: `+` (birleştirme), `*` (tekrarlama), `in` (eleman kontrolü).
- **Metotlar**:

In [ ]:
# Liste oluşturma
a = [1, 2, 3]
b = ["Bahar", 2, 3, [4, 5]]
bos_liste = []
bos_liste2 = list()

# Eleman değiştirme (mutable)
print("İlk liste a:", a)
a[1] = 5
print("a[1]=5 sonrası a:", a)

# İndeksleme ve Dilimleme
print("b'nin ilk elemanı:", b[0])
print("b'nin içindeki listenin ikinci elemanı:", b[3][1])
print("b'nin 1 ve 2. indeksleri:", b[1:3])

# Operatörler
c = [6, 7, 8]
d = b + c
print("b + c:", d)
print("[10] * 5:", [10] * 5)
print("3, b listesinde var mı?", 3 in b)
print("10, b listesinde var mı?", 10 in b)

# Liste Metotları
zz = ['a', 'b', 'c']
print("\nListe Metotları:")
print("Başlangıç zz:", zz)
zz.append('d') # Sona ekleme
print("zz.append('d') sonrası:", zz)
zz.extend(['e', 'f']) # Başka liste elemanlarını sona ekleme
print("zz.extend(['e', 'f']) sonrası:", zz)
zz.insert(1, 'YENI') # 1. indekse ekleme
print("zz.insert(1, 'YENI') sonrası:", zz)
cikan_eleman = zz.pop(2) # 2. indeksteki elemanı çıkar ve döndür ('b')
print(f"zz.pop(2) -> '{cikan_eleman}', sonrası zz: {zz}")
zz.remove('YENI') # 'YENI' değerini listeden çıkar
print("zz.remove('YENI') sonrası:", zz)
rakamlar = [5, 1, 9, 3]
print("Sıralanmamış rakamlar:", rakamlar)
rakamlar.sort() # Yerinde sıralama
print("rakamlar.sort() sonrası:", rakamlar)
rakamlar.sort(reverse=True) # Yerinde tersten sıralama
print("rakamlar.sort(reverse=True) sonrası:", rakamlar)
print("Toplamları (sum(rakamlar)):", sum(rakamlar))

İlk liste a: [1, 2, 3]
a[1]=5 sonrası a: [1, 5, 3]
b'nin ilk elemanı: Bahar
b'nin içindeki listenin ikinci elemanı: 5
b'nin 1 ve 2. indeksleri: [2, 3]
b + c: ['Bahar', 2, 3, [4, 5], 6, 7, 8]
[10] * 5: [10, 10, 10, 10, 10]
3, b listesinde var mı? True
10, b listesinde var mı? False

Liste Metotları:
Başlangıç zz: ['a', 'b', 'c']
zz.append('d') sonrası: ['a', 'b', 'c', 'd']
zz.extend(['e', 'f']) sonrası: ['a', 'b', 'c', 'd', 'e', 'f']
zz.insert(1, 'YENI') sonrası: ['a', 'YENI', 'b', 'c', 'd', 'e', 'f']
zz.pop(2) -> 'b', sonrası zz: ['a', 'YENI', 'c', 'd', 'e', 'f']
zz.remove('YENI') sonrası: ['a', 'c', 'd', 'e', 'f']
Sıralanmamış rakamlar: [5, 1, 9, 3]
rakamlar.sort() sonrası: [1, 3, 5, 9]
rakamlar.sort(reverse=True) sonrası: [9, 5, 3, 1]
Toplamları (sum(rakamlar)): 18


### Listelerde Atama ve Kopyalama Dikkat!
- `liste2 = liste1`: İki değişken aynı listeyi işaret eder. Birindeki değişiklik diğerini etkiler (aliasing).
- `liste2 = liste1[:]` veya `liste2 = liste1.copy()` veya `import copy; liste2 = copy.deepcopy(liste1)`: Listenin bir kopyasını oluşturur. Değişiklikler birbirini etkilemez.

In [ ]:
# Aliasing (Takma Ad Kullanımı)
list1 = [1, 2, 3]
list2 = list1
list2[0] = 99
print("Aliasing Sonrası:")
print("list1:", list1) # list1 de değişti!
print("list2:", list2)

# Kopyalama (Slicing ile - shallow copy)
list3 = [10, 20, 30]
list4 = list3[:]
list4[0] = 88
print("\nKopyalama Sonrası:")
print("list3:", list3) # list3 değişmedi
print("list4:", list4)

Aliasing Sonrası:
list1: [99, 2, 3]
list2: [99, 2, 3]

Kopyalama Sonrası:
list3: [10, 20, 30]
list4: [88, 20, 30]


## 10. Sözlükler (Dictionaries)

- Anahtar-Değer (key-value) çiftlerinden oluşan, sırasız (Python 3.7+ itibarıyla sıralı) ve **değiştirilebilir** (mutable) koleksiyonlardır.
- Süslü parantez `{}` ile tanımlanır: `{'anahtar1': deger1, 'anahtar2': deger2}`.
- Anahtarlar (keys) benzersiz ve değiştirilemez (immutable - string, sayı, tuple) olmalıdır.
- Değerlere (values) anahtarları ile erişilir.
- **Metotlar**:

In [ ]:
# Sözlük oluşturma
z = {'bir':'birinci', 'iki': 'ikinci', 'uc':'ucuncu'}
bos_sozluk = {}
bos_sozluk2 = dict()

# Değere erişim
print("z['iki']:", z['iki'])
# print(z['dört']) # Hata verir (KeyError)
print("z.get('uc'):", z.get('uc'))
print("z.get('dört'):", z.get('dört')) # Hata vermez, None döndürür
print("z.get('dört', 'Bulunamadı'):", z.get('dört', 'Bulunamadı')) # Varsayılan değer

# Eleman ekleme / güncelleme
z['ders'] = "web"
z['ad'] = "mehmet"
z['bir'] = "1."
print("\nGüncellenmiş Sözlük z:", z)

# Uzunluk
print("Sözlüğün uzunluğu (len(z)):", len(z))

# Anahtar kontrolü
print("'ders' anahtarı z'de var mı?", 'ders' in z)
print("'bes' anahtarı z'de var mı?", 'bes' in z)

# Metotlar
print("\nSözlük Metotları:")
print("z.keys():", z.keys()) # Anahtarlar
print("z.values():", z.values()) # Değerler
print("z.items():", z.items()) # (Anahtar, Değer) çiftleri

# Değer kontrolü
degerler = z.values()
print("'web' değeri z'de var mı?", 'web' in degerler)

# Sözlük üzerinde döngü
print("\nSözlük üzerinde for döngüsü (items ile):")
for anahtar, deger in z.items():
    print(f"Anahtar: {anahtar}, Değer: {deger}")

print("\nSözlük üzerinde for döngüsü (sadece anahtarlar):")
for k in z: # Varsayılan olarak anahtarlar üzerinde gezer
    print(f"Anahtar: {k}, Değer: {z[k]}")

z['iki']: ikinci
z.get('uc'): ucuncu
z.get('dört'): None
z.get('dört', 'Bulunamadı'): Bulunamadı

Güncellenmiş Sözlük z: {'bir': '1.', 'iki': 'ikinci', 'uc': 'ucuncu', 'ders': 'web', 'ad': 'mehmet'}
Sözlüğün uzunluğu (len(z)): 5
'ders' anahtarı z'de var mı? True
'bes' anahtarı z'de var mı? False

Sözlük Metotları:
z.keys(): dict_keys(['bir', 'iki', 'uc', 'ders', 'ad'])
z.values(): dict_values(['1.', 'ikinci', 'ucuncu', 'web', 'mehmet'])
z.items(): dict_items([('bir', '1.'), ('iki', 'ikinci'), ('uc', 'ucuncu'), ('ders', 'web'), ('ad', 'mehmet')])
'web' değeri z'de var mı? True

Sözlük üzerinde for döngüsü (items ile):
Anahtar: bir, Değer: 1.
Anahtar: iki, Değer: ikinci
Anahtar: uc, Değer: ucuncu
Anahtar: ders, Değer: web
Anahtar: ad, Değer: mehmet

Sözlük üzerinde for döngüsü (sadece anahtarlar):
Anahtar: bir, Değer: 1.
Anahtar: iki, Değer: ikinci
Anahtar: uc, Değer: ucuncu
Anahtar: ders, Değer: web
Anahtar: ad, Değer: mehmet


## 11. Tuple'lar (Demetler)

- Sıralı ve **değiştirilemez** (immutable) eleman koleksiyonlarıdır.
- Normal parantez `()` ile veya sadece virgülle ayrılarak tanımlanır.
- Tek elemanlı tuple için sona virgül konur: `(eleman,)` veya `eleman,`.
- **İndeksleme ve Dilimleme**: Listeler ve string'ler gibidir.
- Değişmezlikleri nedeniyle sözlük anahtarı olarak kullanılabilirler.

In [ ]:
# Tuple oluşturma
t1 = ('a', 'b', 'c', 'd', 'e')
t2 = 'a', 'b', 'c'
t3 = ('a',) # Tek elemanlı tuple
t4 = tuple('Bahar') # String'den tuple oluşturma

print("t1:", t1)
print("t2:", t2)
print("t3:", t3)
print("t4:", t4)
print("t4 tipi:", type(t4))

# İndeksleme ve Dilimleme
print("t4[0]:", t4[0])
print("t4[1:3]:", t4[1:3])

# Değiştirilemezlik (Hata verir - yorumda bırakıldı)
# t4[0] = 'C' # TypeError: 'tuple' object does not support item assignment

# Tuple birleştirme (yeni tuple oluşturur)
yeni_t = ('x',) + t4
print("Yeni tuple:", yeni_t)

# Tuple Packing ve Unpacking
x = 5
y = 10
print(f"\nTakas öncesi: x={x}, y={y}")
x, y = y, x # Tuple unpacking ile takas
print(f"Takas sonrası: x={x}, y={y}")

mail = 'baharcelik@duzce.edu.tr'
isim, domain = mail.split('@') # split list döndürür, unpacking ile atanır
print(f"İsim: {isim}, Domain: {domain}")

# Fonksiyonun birden fazla değer döndürmesi (tuple olarak)
bolum, kalan = divmod(17, 5)
print(f"17/5 -> Bölüm: {bolum}, Kalan: {kalan}")

t1: ('a', 'b', 'c', 'd', 'e')
t2: ('a', 'b', 'c')
t3: ('a',)
t4: ('B', 'a', 'h', 'a', 'r')
t4 tipi: <class 'tuple'>
t4[0]: B
t4[1:3]: ('a', 'h')
Yeni tuple: ('x', 'B', 'a', 'h', 'a', 'r')

Takas öncesi: x=5, y=10
Takas sonrası: x=10, y=5
İsim: baharcelik, Domain: duzce.edu.tr
17/5 -> Bölüm: 3, Kalan: 2


## 12. Global ve Lokal Değişkenler

- **Lokal Değişken**: Bir fonksiyon içinde tanımlanan ve sadece o fonksiyon içinde erişilebilen değişkendir.
- **Global Değişken**: Fonksiyonların dışında tanımlanan ve programın her yerinden (fonksiyon içleri dahil) erişilebilen değişkendir.
- Fonksiyon içinde global bir değişkene sadece okunarak erişilebilir.
- Fonksiyon içinde global bir değişkenin **değeri değiştirilmek** isteniyorsa, fonksiyon içinde `global degisken_adi` ifadesi kullanılmalıdır.
- **Önemli Not**: Listeler ve sözlükler gibi değiştirilebilir (mutable) nesnelerin *içeriği*, `global` anahtar kelimesi kullanılmadan da fonksiyon içinde değiştirilebilir. Ancak listeyi veya sözlüğü tamamen başka bir listeyle/sözlükle değiştirmek (yeniden atamak) için `global` gerekir.

In [ ]:
sayac = 0 # Global değişken
liste_global = [10, 20, 30] # Global liste

def artir_ve_goster():
    # sayac += 1 # Hata verir! Global değişkeni doğrudan değiştiremez.
    lokal_sayac = sayac + 1 # Okuyabilir, yeni lokal değişkene atayabilir.
    print("Fonksiyon içi (lokal_sayac):", lokal_sayac)

def gercekten_artir():
    global sayac # Global değişkeni değiştireceğimizi belirtiyoruz.
    sayac += 1
    print("Fonksiyon içi (gercekten_artir - global sayac):", sayac)

def listeyi_degistir():
    # global liste_global # Gerekli değil, listenin içeriğini değiştiriyoruz.
    liste_global[0] = 99 # Listenin içeriği değişir.
    # liste_global = [1, 2] # Eğer böyle yeniden atama yapsaydık 'global' gerekirdi.
    print("Fonksiyon içi (liste_global):", liste_global)

print("Başlangıç (sayac):", sayac)
artir_ve_goster()
print("artir_ve_goster sonrası (sayac):", sayac) # Değişmedi
gercekten_artir()
print("gercekten_artir sonrası (sayac):", sayac) # Değişti

print("\nBaşlangıç (liste_global):", liste_global)
listeyi_degistir()
print("listeyi_degistir sonrası (liste_global):", liste_global) # Değişti

Başlangıç (sayac): 0
Fonksiyon içi (lokal_sayac): 1
artir_ve_goster sonrası (sayac): 0
Fonksiyon içi (gercekten_artir - global sayac): 1
gercekten_artir sonrası (sayac): 1

Başlangıç (liste_global): [10, 20, 30]
Fonksiyon içi (liste_global): [99, 20, 30]
listeyi_degistir sonrası (liste_global): [99, 20, 30]


## 13. `zip` ve `enumerate`

- **`zip(*iterables)`**: Birden fazla listeyi, tuple'ı vb. alır ve karşılıklı elemanlarından oluşan tuple'lar üreten bir *iterator* döndürür. En kısa olan iterable'ın uzunluğu kadar ilerler.
- **`enumerate(iterable, start=0)`**: Bir iterable alır ve `(index, eleman)` şeklinde tuple'lar üreten bir *iterator* döndürür.

In [ ]:
# zip örneği
isimler = ['Ali', 'Veli', 'Ayşe']
yaslar = [30, 25, 28]
meslekler = ['Mühendis', 'Öğretmen', 'Doktor']

print("zip kullanarak listeleri birleştirme:")
for isim, yas, meslek in zip(isimler, yaslar, meslekler):
    print(f"İsim: {isim}, Yaş: {yas}, Meslek: {meslek}")

# enumerate örneği
print("\nenumerate kullanarak indekslerle gezinme:")
for index, isim in enumerate(isimler):
    print(f"{index}. index: {isim}")

# enumerate ile başlangıç indeksi belirtme
print("\nenumerate(..., start=1) ile:")
for i, meslek in enumerate(meslekler, start=1):
    print(f"{i}. meslek: {meslek}")

zip kullanarak listeleri birleştirme:
İsim: Ali, Yaş: 30, Meslek: Mühendis
İsim: Veli, Yaş: 25, Meslek: Öğretmen
İsim: Ayşe, Yaş: 28, Meslek: Doktor

enumerate kullanarak indekslerle gezinme:
0. index: Ali
1. index: Veli
2. index: Ayşe

enumerate(..., start=1) ile:
1. meslek: Mühendis
2. meslek: Öğretmen
3. meslek: Doktor


## 14. Dosya İşlemleri

- **Dosya Açma (`open`)**: `dosya_nesnesi = open('dosya_adi.txt', 'mod')`
  - **Modlar**:
    - `'r'`: Okuma (varsayılan). Dosya yoksa hata verir.
    - `'w'`: Yazma. Dosya varsa içeriğini siler, yoksa oluşturur.
    - `'a'`: Ekleme (append). Dosya varsa sonuna ekler, yoksa oluşturur.
    - `'r+'`: Okuma ve yazma.
    - `'b'`: İkili (binary) mod (örn: resim dosyaları için).
- **Dosyaya Yazma (`write`)**: `dosya_nesnesi.write(metin)`
  - Yazılacak verinin string olması gerekir. `str()` ile dönüşüm yapılabilir.
  - Yeni satır için `\n` karakteri kullanılır.
- **Dosyayı Kapatma (`close`)**: `dosya_nesnesi.close()`. Kaynakları serbest bırakmak ve verinin dosyaya yazıldığından emin olmak için önemlidir.
- **`with open(...) as ...:`**: Dosyayı otomatik kapatan, daha güvenli bir yöntemdir.

In [ ]:
# Dosyaya yazma ('w' modu - eski içerik silinir)
try:
    # Google Colab'da dosya yolu direkt isimle verilebilir.
    # Yerel makinede Desktop/ gibi yollar yerine tam yol gerekebilir.
    fout = open("yazmalik_dosya.txt", 'w', encoding='utf-8') # Türkçe karakterler için encoding
    satir1 = "Bu ilk satır.\n"
    satir2 = "Bu da ikinci satır.\n"
    fout.write(satir1)
    fout.write(satir2)
    fout.write("Sayı: " + str(52) + "\n") # Sayıyı string'e çevirip yazma

    # Eski stil formatlama ile yazma
    fout.write('%d aydır çalışıyorum, sınavdan %g %s.\n' % (3, 82.5, 'aldım'))

    # f-string ile yazma (daha modern)
    isim = "Ahmet"
    puan = 75.5
    fout.write(f"{isim}, {puan} puan aldı.\n")

    fout.close() # Dosyayı kapatma
    print("'yazmalik_dosya.txt' dosyası yazıldı.")

except Exception as e:
    print(f"Dosya yazma hatası: {e}")

# with open ile dosyaya ekleme ('a' modu)
try:
    with open("yazmalik_dosya.txt", 'a', encoding='utf-8') as fa:
        fa.write("Bu satır sona eklendi.\n")
        fa.write("Bu da eklendi.\n")
    # 'with' bloğu bittiğinde dosya otomatik kapanır.
    print("'yazmalik_dosya.txt' dosyasına ekleme yapıldı.")
except Exception as e:
    print(f"Dosya ekleme hatası: {e}")

# Dosyadan okuma ('r' modu)
try:
    with open("yazmalik_dosya.txt", 'r', encoding='utf-8') as fin:
        print("\nDosya İçeriği Okunuyor:")
        #icerik = fin.read() # Tüm içeriği tek string olarak okur
        #print(icerik)

        # Satır satır okuma
        for satir in fin:
            print("> " + satir.strip()) # strip() baştaki/sondaki boşlukları ve satır sonu karakterini temizler

except FileNotFoundError:
    print("Okunacak dosya bulunamadı!")
except Exception as e:
    print(f"Dosya okuma hatası: {e}")

'yazmalik_dosya.txt' dosyası yazıldı.
'yazmalik_dosya.txt' dosyasına ekleme yapıldı.

Dosya İçeriği Okunuyor:
> Bu ilk satır.
> Bu da ikinci satır.
> Sayı: 52
> 3 aydır çalışıyorum, sınavdan 82.5 aldım.
> Ahmet, 75.5 puan aldı.
> Bu satır sona eklendi.
> Bu da eklendi.


## 15. `os` Modülü

- İşletim sistemi ile ilgili işlemler yapmak için kullanılır.
- `os.getcwd()`: Geçerli çalışma dizinini (Current Working Directory - CWD) verir.
- `os.listdir()`: Bulunulan dizindeki dosya ve klasörleri listeler.
- `os.path.exists(yol)`: Belirtilen yolun (dosya veya klasör) var olup olmadığını kontrol eder.
- `os.path.isfile(yol)`: Yolun bir dosya olup olmadığını kontrol eder.
- `os.path.isdir(yol)`: Yolun bir klasör olup olmadığını kontrol eder.
- `os.path.abspath(yol)`: Göreceli bir yolun mutlak (tam) yolunu verir.

In [ ]:
import os

# Geçerli çalışma dizini
cwd = os.getcwd()
print(f"Geçerli Çalışma Dizini (CWD): {cwd}")

# Dizindeki dosyaları listeleme
print("\nCWD İçeriği:")
try:
    icerik = os.listdir(cwd)
    print(icerik)
except Exception as e:
    print(f"Dizin listeleme hatası: {e}")

# Dosya ve klasör kontrolü
dosya_adi = "yazmalik_dosya.txt"
klasor_adi = "ornek_klasor"

print(f"\n'{dosya_adi}' var mı? {os.path.exists(dosya_adi)}")
print(f"'{dosya_adi}' bir dosya mı? {os.path.isfile(dosya_adi)}")
print(f"'{dosya_adi}' bir klasör mü? {os.path.isdir(dosya_adi)}")

# Olmayan bir klasörü kontrol edelim
print(f"'{klasor_adi}' var mı? {os.path.exists(klasor_adi)}")

# Mutlak yol
print(f"'{dosya_adi}' mutlak yolu: {os.path.abspath(dosya_adi)}")

Geçerli Çalışma Dizini (CWD): /content

CWD İçeriği:
['.config', 'yazmalik_dosya.txt', 'sample_data']

'yazmalik_dosya.txt' var mı? True
'yazmalik_dosya.txt' bir dosya mı? True
'yazmalik_dosya.txt' bir klasör mü? False
'ornek_klasor' var mı? False
'yazmalik_dosya.txt' mutlak yolu: /content/yazmalik_dosya.txt


# NumPy - Numerical Python

## 1. Giriş ve Kurulum

- NumPy, Python'da bilimsel ve matematiksel hesaplamalar için temel kütüphanedir.
- Çok boyutlu diziler (array'ler) ve matrisler üzerinde yüksek performanslı işlemler sunar.
- Veri analizi, makine öğrenmesi gibi alanlarda sıklıkla kullanılır.
- `import numpy as np` komutu ile kütüphaneyi `np` kısaltmasıyla projemize dahil ederiz.

In [ ]:
import numpy as np
import platform # Sistem bilgisini almak için

print('Python version: ' + platform.python_version())
print('NumPy version: ' + np.__version__)

Python version: 3.11.12
NumPy version: 2.0.2


## 2. NumPy Veri Tipleri (dtypes)

- NumPy dizilerindeki tüm elemanlar aynı veri tipinde olmalıdır.
- Bu, bellek verimliliği ve işlem hızı sağlar.
- **Yaygın Tipler**:
  - `int32`, `int64`: Tam sayılar.
  - `float32`, `float64`: Ondalıklı sayılar.
  - `complex64`, `complex128`: Karmaşık sayılar.
  - `bool`: `True` / `False`.
  - `object`: Farklı tipleri barındırabilen esnek tip.
  - `string_` (`S`): Belirli byte uzunluğundaki metinler (örn: `S10` - max 10 byte).
  - `unicode_` (`U`): Unicode karakterler için metinler (örn: `U10` - max 10 karakter).
- `dtype` parametresi ile dizi oluştururken tip belirlenebilir.
- `arr.dtype` ile dizinin tipi öğrenilebilir.
- `arr.astype(yeni_tip)` ile tip dönüşümü yapılabilir (yeni dizi döner).

In [ ]:
# Farklı dtype'lar ile dizi oluşturma
arr_float = np.array([1, 2, 3], dtype='f4') # float32
arr_complex = np.array([1+2j, 3-4j], dtype='c8') # complex64
arr_bool = np.array([0, 1, 1, 0], dtype="bool") # 0 -> False, diğer sayılar -> True
arr_str = np.array(['abc', 'defg'], dtype='S3') # max 3 byte, 'defg' -> 'def'

print("Float Dizi:", arr_float, " Tipi:", arr_float.dtype)
print("Complex Dizi:", arr_complex, " Tipi:", arr_complex.dtype)
print("Boolean Dizi:", arr_bool, " Tipi:", arr_bool.dtype)
print("String Dizi:", arr_str, " Tipi:", arr_str.dtype)

# Otomatik tip belirleme (genelde en kapsayıcı tip seçilir)
arr_mix = np.array([1, 2.5, 3]) # İçinde float olduğu için hepsi float64 olur
print("\nMix Dizi:", arr_mix, " Tipi:", arr_mix.dtype)

# Tip Dönüşümü
arr_int = np.array([1, 2, 3, 4])
print("\nInt Dizi:", arr_int, " Tipi:", arr_int.dtype)
arr_float_conv = arr_int.astype(np.float64)
print("astype(float64) sonrası:", arr_float_conv, " Tipi:", arr_float_conv.dtype)

# Pandas ile dtype listesi (orijinal notebook'taki gibi)
import pandas as pd
dtypes = pd.DataFrame(
 {
 'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
 'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
 }
)
print("\nNumPy Veri Tipleri:")
print(dtypes)

Float Dizi: [1. 2. 3.]  Tipi: float32
Complex Dizi: [1.+2.j 3.-4.j]  Tipi: complex64
Boolean Dizi: [False  True  True False]  Tipi: bool
String Dizi: [b'abc' b'def']  Tipi: |S3

Mix Dizi: [1.  2.5 3. ]  Tipi: float64

Int Dizi: [1 2 3 4]  Tipi: int64
astype(float64) sonrası: [1. 2. 3. 4.]  Tipi: float64

NumPy Veri Tipleri:
          Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U


## 3. NumPy Dizisi (Array) Oluşturma Yöntemleri

- **`np.array(liste)`**: Python listelerinden veya tuple'larından dizi oluşturur.
- **`np.arange(start, stop, step)`**: Belirtilen aralıkta dizi oluşturur (`stop` hariç).
- **`np.linspace(start, stop, num)`**: `start` ve `stop` arasında (`stop` dahil) `num` adet eşit aralıklı eleman oluşturur.
- **`np.zeros(shape)`**: Belirtilen şekilde (boyutta) 0'lardan oluşan dizi.
- **`np.ones(shape)`**: Belirtilen şekilde 1'lerden oluşan dizi.
- **`np.full(shape, fill_value)`**: Belirtilen şekilde, belirtilen değerle dolu dizi.
- **`np.eye(N)`**: N x N boyutlu birim matris.
- **`np.random.rand(d0, d1, ...)`**: 0-1 arasında uniform dağılımlı rastgele sayılar.
- **`np.random.randn(d0, d1, ...)`**: Standart normal dağılımlı (ortalama 0, varyans 1) rastgele sayılar.
- **`np.random.randint(low, high, size)`**: `low` (dahil) ile `high` (hariç) arasında rastgele tam sayılar.

In [ ]:
# Listeden array oluşturma
liste1 = [1, 2, 3, 4, 5]
arr1 = np.array(liste1)
print("Listeden oluşturulan arr1:", arr1)

liste2 = [[1, 2], [3, 4]]
arr2 = np.array(liste2)
print("İç içe listeden oluşturulan arr2:\n", arr2)

# arange ile array oluşturma
arr3 = np.arange(0, 10, 2) # 0'dan 10'a kadar 2'şer artan
print("\nnp.arange(0, 10, 2):", arr3)

# linspace ile array oluşturma
arr4 = np.linspace(0, 5, 6) # 0 ile 5 arasında 6 eleman
print("\nnp.linspace(0, 5, 6):", arr4)

# zeros, ones, full, eye
arr_zeros = np.zeros((2, 3))
print("\nnp.zeros((2, 3)):\n", arr_zeros)

arr_ones = np.ones((3, 2))
print("\nnp.ones((3, 2)):\n", arr_ones)

arr_full = np.full((2, 2), 99)
print("\nnp.full((2, 2), 99):\n", arr_full)

arr_eye = np.eye(4)
print("\nnp.eye(4):\n", arr_eye)

# Rastgele sayılar
arr_rand = np.random.rand(2, 2) # 0-1 arası uniform
print("\nnp.random.rand(2, 2):\n", arr_rand)

arr_randn = np.random.randn(2, 2) # Standart normal dağılım
print("\nnp.random.randn(2, 2):\n", arr_randn)

arr_randint = np.random.randint(10, 20, size=(3, 3)) # 10-19 arası tamsayılar
print("\nnp.random.randint(10, 20, size=(3, 3)):\n", arr_randint)

Listeden oluşturulan arr1: [1 2 3 4 5]
İç içe listeden oluşturulan arr2:
 [[1 2]
 [3 4]]

np.arange(0, 10, 2): [0 2 4 6 8]

np.linspace(0, 5, 6): [0. 1. 2. 3. 4. 5.]

np.zeros((2, 3)):
 [[0. 0. 0.]
 [0. 0. 0.]]

np.ones((3, 2)):
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

np.full((2, 2), 99):
 [[99 99]
 [99 99]]

np.eye(4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

np.random.rand(2, 2):
 [[0.22398245 0.28744858]
 [0.65948928 0.80917685]]

np.random.randn(2, 2):
 [[-0.24081262 -1.8602911 ]
 [ 0.45815097 -0.40503673]]

np.random.randint(10, 20, size=(3, 3)):
 [[13 13 18]
 [15 16 13]
 [19 13 10]]


## 4. Dizi Özellikleri (Attributes)

- **`arr.ndim`**: Boyut sayısı (eksen sayısı).
- **`arr.shape`**: Her boyuttaki eleman sayısı (tuple olarak).
- **`arr.size`**: Toplam eleman sayısı.
- **`arr.dtype`**: Elemanların veri tipi.

In [ ]:
arr = np.random.randint(0, 10, size=(3, 4))
print("Örnek Dizi arr:\n", arr)

print("\nBoyut Sayısı (ndim):", arr.ndim)
print("Şekil (shape):", arr.shape)
print("Toplam Eleman Sayısı (size):", arr.size)
print("Veri Tipi (dtype):", arr.dtype)

Örnek Dizi arr:
 [[5 7 8 0]
 [1 7 6 6]
 [6 3 6 3]]

Boyut Sayısı (ndim): 2
Şekil (shape): (3, 4)
Toplam Eleman Sayısı (size): 12
Veri Tipi (dtype): int64


## 5. Yeniden Şekillendirme (`reshape`, `resize`)

- **`arr.reshape(yeni_sekil)`**: Dizinin toplam eleman sayısını değiştirmeden boyutlarını yeniden düzenler. Orijinal diziyi değiştirmez, yeni bir dizi (genellikle görünüm/view) döndürür.
  - `yeni_sekil` tuple olarak verilir (örn: `(4, 3)`).
  - Boyutlardan biri `-1` olarak verilirse, diğer boyutlara göre otomatik hesaplanır.
- **`arr.resize(yeni_sekil)`**: Diziyi yerinde (in-place) yeniden şekillendirir. Orijinal diziyi değiştirir. Eleman sayısı değişirse dikkatli kullanılmalıdır.

In [ ]:
arr = np.arange(12)
print("Başlangıç dizisi arr:", arr)
print("arr.shape:", arr.shape)

# reshape kullanımı (orijinali değiştirmez)
arr_reshaped = arr.reshape((3, 4))
print("\narr.reshape((3, 4)):\n", arr_reshaped)
print("reshape sonrası arr:", arr) # Orijinal değişmedi
print("arr_reshaped.shape:", arr_reshaped.shape)

# reshape'de -1 kullanımı
arr_reshaped_auto = arr.reshape((2, -1)) # Satır 2 olsun, sütunu kendi hesaplasın (6)
print("\narr.reshape((2, -1)):\n", arr_reshaped_auto)
print("arr_reshaped_auto.shape:", arr_reshaped_auto.shape)

# resize kullanımı (orijinali değiştirir)
arr_for_resize = np.arange(6)
print("\nBaşlangıç arr_for_resize:", arr_for_resize)
arr_for_resize.resize((2, 3)) # Yerinde değiştirir
print("resize((2, 3)) sonrası arr_for_resize:\n", arr_for_resize)

Başlangıç dizisi arr: [ 0  1  2  3  4  5  6  7  8  9 10 11]
arr.shape: (12,)

arr.reshape((3, 4)):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
reshape sonrası arr: [ 0  1  2  3  4  5  6  7  8  9 10 11]
arr_reshaped.shape: (3, 4)

arr.reshape((2, -1)):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
arr_reshaped_auto.shape: (2, 6)

Başlangıç arr_for_resize: [0 1 2 3 4 5]
resize((2, 3)) sonrası arr_for_resize:
 [[0 1 2]
 [3 4 5]]


## 6. İndeksleme ve Dilimleme (Indexing & Slicing)

- **Tek Boyutlu Diziler**: Python listeleri gibidir.
  - `arr[index]`
  - `arr[start:stop:step]`
- **Çok Boyutlu Diziler**: Her boyut için indeks veya dilim virgülle ayrılır.
  - `arr[satir_index, sutun_index]`
  - `arr[satir_dilimi, sutun_dilimi]`
- **Önemli Not**: Dilimleme ile elde edilen alt diziler (slice'lar) orijinal dizinin bir **görünümüdür (view)**. Alt dizide yapılan değişiklikler orijinal diziyi de etkiler! Bağımsız bir kopya isteniyorsa `.copy()` metodu kullanılmalıdır.

In [ ]:
# 2 Boyutlu dizi oluşturalım
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2 Boyutlu Dizi arr2d:\n", arr2d)

# Tek elemana erişim
print("\narr2d[1, 2] (1. satır, 2. sütun):", arr2d[1, 2]) # Çıktı: 6
print("arr2d[0][1] (alternatif yol):", arr2d[0][1]) # Çıktı: 2

# Dilimleme
print("\narr2d[:2, 1:] (ilk 2 satır, 1. sütundan sona kadar):\n", arr2d[:2, 1:])
# Çıktı:
# [[2 3]
#  [5 6]]

print("\narr2d[1, :] (1. satırın tamamı):", arr2d[1, :]) # Çıktı: [4 5 6]
print("arr2d[:, 1] (1. sütunun tamamı):", arr2d[:, 1]) # Çıktı: [2 5 8]

# Dilimlemenin view (görünüm) olduğunu gösterme
arr2d_slice = arr2d[:2, :2] # İlk 2 satır, ilk 2 sütun
print("\nOrijinal dilim arr2d_slice:\n", arr2d_slice)

arr2d_slice[0, 0] = 99 # Dilim üzerinde değişiklik yapalım
print("\nDilim değiştirildikten sonra arr2d_slice:\n", arr2d_slice)
print("\nDilim değiştirildikten sonra ORİJİNAL arr2d:\n", arr2d) # Orijinal dizi de değişti!

# Kopya oluşturma
arr2d_copy = arr2d[:2, 1:].copy() # Bağımsız kopya
arr2d_copy[0, 0] = 111 # Kopyayı değiştirelim
print("\nKopya arr2d_copy:\n", arr2d_copy)
print("\nKopya değiştirildikten sonra ORİJİNAL arr2d:\n", arr2d) # Orijinal dizi değişmedi

2 Boyutlu Dizi arr2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

arr2d[1, 2] (1. satır, 2. sütun): 6
arr2d[0][1] (alternatif yol): 2

arr2d[:2, 1:] (ilk 2 satır, 1. sütundan sona kadar):
 [[2 3]
 [5 6]]

arr2d[1, :] (1. satırın tamamı): [4 5 6]
arr2d[:, 1] (1. sütunun tamamı): [2 5 8]

Orijinal dilim arr2d_slice:
 [[1 2]
 [4 5]]

Dilim değiştirildikten sonra arr2d_slice:
 [[99  2]
 [ 4  5]]

Dilim değiştirildikten sonra ORİJİNAL arr2d:
 [[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]

Kopya arr2d_copy:
 [[111   3]
 [  5   6]]

Kopya değiştirildikten sonra ORİJİNAL arr2d:
 [[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]


## 7. Boolean İndeksleme

- Bir koşul ifadesi (örn: `arr > 5`) kullanarak dizi elemanlarını filtrelemektir.
- Koşul ifadesi, orijinal diziyle aynı boyutta bir boolean (`True`/`False`) dizi döndürür.
- Bu boolean dizi, indeks olarak kullanıldığında sadece `True`'ya karşılık gelen elemanlar seçilir (sonuç genellikle 1 boyutlu olur).
- Mantıksal operatörler `&` (VE) ve `|` (VEYA) ile birden fazla koşul birleştirilebilir (parantezlere dikkat!).
- `np.where(kosul, deger_dogruysa, deger_yanlissa)`: Koşula göre elemanları farklı değerlerle değiştiren yeni bir dizi oluşturur.
- `np.argwhere(kosul)`: Koşulu sağlayan elemanların indekslerini (satır, sütun şeklinde) verir.

In [ ]:
arr = np.arange(1, 17).reshape((4, 4))
print("Dizi arr:\n", arr)

# Koşul oluşturma
kosul = arr > 10
print("\nKoşul (arr > 10):\n", kosul)

# Boolean indeksleme ile eleman seçme
secilenler = arr[kosul] # veya arr[arr > 10]
print("\nKoşulu sağlayan elemanlar (arr[arr > 10]):", secilenler)

# Birden fazla koşul
cift_ve_kucuk10 = arr[(arr % 2 == 0) & (arr < 10)]
print("\n10'dan küçük çift sayılar:", cift_ve_kucuk10)

# np.where kullanımı
arr_where = np.where(arr > 8, -1, arr) # 8'den büyükse -1, değilse kendi değeri
print("\nnp.where(arr > 8, -1, arr):\n", arr_where)

# np.argwhere kullanımı
indeksler = np.argwhere(arr > 12)
print("\n12'den büyük elemanların indeksleri (np.argwhere(arr > 12)):\n", indeksler)

Dizi arr:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Koşul (arr > 10):
 [[False False False False]
 [False False False False]
 [False False  True  True]
 [ True  True  True  True]]

Koşulu sağlayan elemanlar (arr[arr > 10]): [11 12 13 14 15 16]

10'dan küçük çift sayılar: [2 4 6 8]

np.where(arr > 8, -1, arr):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]

12'den büyük elemanların indeksleri (np.argwhere(arr > 12)):
 [[3 0]
 [3 1]
 [3 2]
 [3 3]]


## 8. Fancy İndeksleme

- İndeks olarak tam sayı listeleri veya dizileri kullanarak eleman seçmektir.
- Belirli satırları, belirli sütunları veya belirli koordinatlardaki elemanları seçmek için kullanılır.
- Boolean indekslemenin aksine, sonuç her zaman orijinal dizinin bir **kopyasıdır**.

In [ ]:
arr = np.arange(25).reshape((5, 5))
print("Dizi arr:\n", arr)

# Belirli satırları seçme
secilen_satirlar = arr[[0, 2, 4]] # 0., 2. ve 4. satırlar
print("\narr[[0, 2, 4]]:\n", secilen_satirlar)

# Belirli sütunları seçme
secilen_sutunlar = arr[:, [1, 3]] # Tüm satırlar, 1. ve 3. sütunlar
print("\narr[:, [1, 3]]:\n", secilen_sutunlar)

# Belirli koordinatlardaki elemanları seçme
secilen_elemanlar = arr[[0, 1, 2], [1, 3, 0]] # (0,1), (1,3) ve (2,0) elemanları
print("\narr[[0, 1, 2], [1, 3, 0]]:", secilen_elemanlar)

# Satır ve sütunları fancy indeksleme ile birleştirme
# 1. ve 3. satırların, 0. ve 4. sütunlarını seçme
alt_matris = arr[[1, 3]][:, [0, 4]]
print("\narr[[1, 3]][:, [0, 4]]:\n", alt_matris)

Dizi arr:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

arr[[0, 2, 4]]:
 [[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]]

arr[:, [1, 3]]:
 [[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]
 [21 23]]

arr[[0, 1, 2], [1, 3, 0]]: [ 1  8 10]

arr[[1, 3]][:, [0, 4]]:
 [[ 5  9]
 [15 19]]


## 9. Evrensel Fonksiyonlar (Universal Functions - ufuncs)

- NumPy dizileri üzerinde eleman bazında (element-wise) hızlı işlemler yapan fonksiyonlardır.

### 9.1. Aritmetik ve Matematiksel ufuncs
- `np.add(arr1, arr2)` veya `arr1 + arr2`
- `np.subtract(arr1, arr2)` veya `arr1 - arr2`
- `np.multiply(arr1, arr2)` veya `arr1 * arr2` (Eleman bazında çarpım! Matris çarpımı değil)
- `np.divide(arr1, arr2)` veya `arr1 / arr2`
- `np.power(arr, us)` veya `arr ** us`
- `np.sqrt(arr)`: Karekök.
- `np.exp(arr)`: $e^{arr}$ (üstel fonksiyon).
- `np.log(arr)`, `np.log10(arr)`, `np.log2(arr)`: Doğal, 10 tabanlı, 2 tabanlı logaritma.
- `np.sin(arr)`, `np.cos(arr)`, `np.tan(arr)`: Trigonometrik fonksiyonlar.
- `np.abs(arr)`: Mutlak değer.
- `np.ceil(arr)`, `np.floor(arr)`, `np.round(arr)`: Yukarı yuvarlama, aşağı yuvarlama, en yakına yuvarlama.
- `np.mod(arr1, arr2)`: Eleman bazında modül.
- `np.maximum(arr1, arr2)`, `np.minimum(arr1, arr2)`: Eleman bazında karşılaştırıp büyük/küçük olanı alır.

In [ ]:
arr = np.arange(1, 5)
print("Dizi arr:", arr)

print("arr + 5:", arr + 5) # Skaler ile işlem
print("arr * 2:", arr * 2)
print("arr ** 2:", arr ** 2)
print("np.sqrt(arr):", np.sqrt(arr))
print("np.exp(arr):", np.exp(arr))

arr1 = np.array([1, 5, 3])
arr2 = np.array([2, 2, 6])
print("\narr1:", arr1)
print("arr2:", arr2)
print("np.maximum(arr1, arr2):", np.maximum(arr1, arr2))

Dizi arr: [1 2 3 4]
arr + 5: [6 7 8 9]
arr * 2: [2 4 6 8]
arr ** 2: [ 1  4  9 16]
np.sqrt(arr): [1.         1.41421356 1.73205081 2.        ]
np.exp(arr): [ 2.71828183  7.3890561  20.08553692 54.59815003]

arr1: [1 5 3]
arr2: [2 2 6]
np.maximum(arr1, arr2): [2 5 6]


### 9.2. İstatistiksel Metotlar ve Eksenler (`axis`)
- `arr.sum()` veya `np.sum(arr)`: Tüm elemanların toplamı.
- `arr.mean()` veya `np.mean(arr)`: Ortalama.
- `arr.std()` veya `np.std(arr)`: Standart sapma.
- `arr.var()` veya `np.var(arr)`: Varyans.
- `arr.min()` veya `np.min(arr)`: Minimum değer.
- `arr.max()` veya `np.max(arr)`: Maksimum değer.
- `arr.argmin()` veya `np.argmin(arr)`: Minimum değerin indeksi (düzleştirilmiş dizide).
- `arr.argmax()` veya `np.argmax(arr)`: Maksimum değerin indeksi (düzleştirilmiş dizide).
- `arr.cumsum()` veya `np.cumsum(arr)`: Kümülatif toplam.
- `arr.cumprod()` veya `np.cumprod(arr)`: Kümülatif çarpım.

- **`axis` Parametresi**: Bu fonksiyonların çoğu `axis` parametresi alır.
  - `axis=0`: İşlemi sütunlar boyunca (dikey) yapar, sonuç her sütun için bir değer olur.
  - `axis=1`: İşlemi satırlar boyunca (yatay) yapar, sonuç her satır için bir değer olur.
  - `axis=None` (varsayılan): İşlemi tüm dizi üzerinde yapar, tek bir sonuç döner.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Dizi arr:\n", arr)

print("arr.sum():", arr.sum()) # Tüm elemanların toplamı (21)
print("arr.mean():", arr.mean()) # Tüm elemanların ortalaması (3.5)
print("arr.max():", arr.max()) # En büyük eleman (6)
print("arr.min():", arr.min()) # En küçük eleman (1)

# Eksen bazında işlemler
print("\narr.sum(axis=0) (Sütun toplamları):", arr.sum(axis=0)) # [1+4, 2+5, 3+6] -> [5 7 9]
print("arr.sum(axis=1) (Satır toplamları):", arr.sum(axis=1)) # [1+2+3, 4+5+6] -> [ 6 15]

print("arr.mean(axis=0) (Sütun ortalamaları):", arr.mean(axis=0))
print("arr.max(axis=1) (Satır maksimumları):", arr.max(axis=1))

print("arr.cumsum(axis=1) (Satır kümülatif toplamları):\n", arr.cumsum(axis=1))
# [[1, 1+2, 1+2+3],
#  [4, 4+5, 4+5+6]] -> [[ 1  3  6], [ 4  9 15]]

Dizi arr:
 [[1 2 3]
 [4 5 6]]
arr.sum(): 21
arr.mean(): 3.5
arr.max(): 6
arr.min(): 1

arr.sum(axis=0) (Sütun toplamları): [5 7 9]
arr.sum(axis=1) (Satır toplamları): [ 6 15]
arr.mean(axis=0) (Sütun ortalamaları): [2.5 3.5 4.5]
arr.max(axis=1) (Satır maksimumları): [3 6]
arr.cumsum(axis=1) (Satır kümülatif toplamları):
 [[ 1  3  6]
 [ 4  9 15]]


## 10. Sıralama (`sort`, `argsort`)

- **`np.sort(arr, axis=-1)`**: Dizinin sıralanmış bir **kopyasını** döndürür.
  - `axis=-1` (varsayılan): Son eksen boyunca (genellikle satırlar) sıralar.
  - `axis=0`: Sütunlar boyunca sıralar.
  - `axis=None`: Diziyi düzleştirip sıralar.
- **`arr.sort(axis=-1)`**: Diziyi yerinde (in-place) sıralar. Değer döndürmez (None).
- **`np.argsort(arr, axis=-1)`**: Diziyi sıralayacak olan **indeksleri** döndürür. Orijinal diziyi değiştirmez.

In [ ]:
arr = np.random.randint(1, 10, size=(3, 4))
print("Sırasız Dizi arr:\n", arr)

# np.sort (kopya döndürür)
arr_sorted_rows = np.sort(arr, axis=1) # Satırları sırala
print("\nSatırları sıralanmış (kopya):\n", arr_sorted_rows)

arr_sorted_cols = np.sort(arr, axis=0) # Sütunları sırala
print("\nSütunları sıralanmış (kopya):\n", arr_sorted_cols)

print("\nnp.sort sonrası orijinal arr:\n", arr) # Orijinal değişmedi

# arr.sort (yerinde sıralar)
arr_copy = arr.copy()
arr_copy.sort(axis=1) # Satırları yerinde sırala
print("\narr.sort(axis=1) sonrası (yerinde):\n", arr_copy)

# np.argsort (indeksleri döndürür)
arr_indices = np.argsort(arr, axis=1) # Satırları sıralayan indeksler
print("\nSatırları sıralayan indeksler (np.argsort(axis=1)):\n", arr_indices)

Sırasız Dizi arr:
 [[1 5 6 1]
 [6 9 5 9]
 [9 9 5 6]]

Satırları sıralanmış (kopya):
 [[1 1 5 6]
 [5 6 9 9]
 [5 6 9 9]]

Sütunları sıralanmış (kopya):
 [[1 5 5 1]
 [6 9 5 6]
 [9 9 6 9]]

np.sort sonrası orijinal arr:
 [[1 5 6 1]
 [6 9 5 9]
 [9 9 5 6]]

arr.sort(axis=1) sonrası (yerinde):
 [[1 1 5 6]
 [5 6 9 9]
 [5 6 9 9]]

Satırları sıralayan indeksler (np.argsort(axis=1)):
 [[0 3 1 2]
 [2 0 1 3]
 [2 3 1 0]]


## 11. Dizi Manipülasyonu

### 11.1. Transpoz (`.T`, `transpose`, `swapaxes`)
- **`arr.T`**: Dizinin transpozunu (satırlarla sütunların yer değiştirmesi) alır. Görünüm (view) döndürür.
- **`np.transpose(arr)`** veya **`arr.transpose()`**: Transpoz alır. Çok boyutlu dizilerde eksenlerin sırasını belirten bir tuple alabilir: `arr.transpose((1, 0, 2))`.
- **`arr.swapaxes(axis1, axis2)`**: Belirtilen iki eksenin yerini değiştirir. Görünüm (view) döndürür.

In [ ]:
arr = np.arange(6).reshape((2, 3))
print("Dizi arr:\n", arr)

print("arr.T (Transpoz):\n", arr.T)

arr3d = np.arange(12).reshape((2, 2, 3))
print("\n3 Boyutlu Dizi arr3d (shape: {}):\n{}".format(arr3d.shape, arr3d))

# Eksen sırasını değiştirme (0, 1, 2) -> (1, 0, 2)
arr_transposed = arr3d.transpose((1, 0, 2))
print("\narr3d.transpose((1, 0, 2)) (shape: {}):\n{}".format(arr_transposed.shape, arr_transposed))

# Eksen değiştirme (swapaxes)
arr_swapped = arr.swapaxes(0, 1)
print("\narr.swapaxes(0, 1):\n", arr_swapped)

Dizi arr:
 [[0 1 2]
 [3 4 5]]
arr.T (Transpoz):
 [[0 3]
 [1 4]
 [2 5]]

3 Boyutlu Dizi arr3d (shape: (2, 2, 3)):
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

arr3d.transpose((1, 0, 2)) (shape: (2, 2, 3)):
[[[ 0  1  2]
  [ 6  7  8]]

 [[ 3  4  5]
  [ 9 10 11]]]

arr.swapaxes(0, 1):
 [[0 3]
 [1 4]
 [2 5]]


### 11.2. Düzleştirme (`flatten`, `ravel`)
- **`arr.flatten()`**: Çok boyutlu diziyi tek boyutlu hale getirir. Her zaman **kopya** döndürür.
- **`arr.ravel()`**: Çok boyutlu diziyi tek boyutlu hale getirir. Mümkünse **görünüm (view)** döndürür (daha verimli), değilse kopya döndürür.

In [ ]:
arr = np.array([[1, 2], [3, 4]])
print("Dizi arr:\n", arr)

arr_flat = arr.flatten()
print("arr.flatten():", arr_flat)
arr_flat[0] = 99 # Kopyayı değiştirmek orijinali etkilemez
print("flatten sonrası orijinal arr:\n", arr)

arr_ravel = arr.ravel()
print("\narr.ravel():", arr_ravel)
arr_ravel[0] = 88 # Görünümü değiştirmek orijinali etkiler
print("ravel sonrası orijinal arr:\n", arr)

Dizi arr:
 [[1 2]
 [3 4]]
arr.flatten(): [1 2 3 4]
flatten sonrası orijinal arr:
 [[1 2]
 [3 4]]

arr.ravel(): [1 2 3 4]
ravel sonrası orijinal arr:
 [[88  2]
 [ 3  4]]


### 11.3. Ekleme, Silme, Araya Ekleme (`append`, `insert`, `delete`)
- **`np.append(arr, values, axis=None)`**: `values`'ı `arr`'ın sonuna ekler. `axis` belirtilmezse diziler düzleştirilip birleştirilir. `axis` belirtilirse, belirtilen eksen boyunca ekleme yapılır (boyutlar uyumlu olmalı). Kopya döndürür.
- **`np.insert(arr, obj, values, axis=None)`**: `values`'ı `arr` içine, `obj` ile belirtilen indeks(ler)den *önce* ekler. Kopya döndürür.
- **`np.delete(arr, obj, axis=None)`**: `arr`'dan `obj` ile belirtilen indeks(ler)deki elemanları/dilimleri siler. Kopya döndürür.

In [ ]:
arr = np.array([1, 2, 3])
print("Dizi arr:", arr)

# append
arr_appended = np.append(arr, [4, 5])
print("np.append(arr, [4, 5]):", arr_appended)

arr2d = np.array([[1,2],[3,4]])
arr_appended_axis0 = np.append(arr2d, [[5,6]], axis=0) # Satır ekleme
print("\nnp.append(axis=0):\n", arr_appended_axis0)
arr_appended_axis1 = np.append(arr2d, [[7],[8]], axis=1) # Sütun ekleme
print("\nnp.append(axis=1):\n", arr_appended_axis1)

# insert
arr_inserted = np.insert(arr, 1, 99) # 1. indeksten önce 99 ekle
print("\nnp.insert(arr, 1, 99):", arr_inserted)
arr_inserted_multi = np.insert(arr, [1, 3], [88, 77]) # 1. ve 3. indexten önce ekle
print("np.insert(arr, [1, 3], [88, 77]):", arr_inserted_multi)

# delete
arr_deleted = np.delete(arr_appended, [0, 2]) # 0. ve 2. indeksteki elemanları sil
print("\nnp.delete(arr_appended, [0, 2]):", arr_deleted)

arr_deleted_axis0 = np.delete(arr_appended_axis0, 1, axis=0) # 1. satırı sil
print("\nnp.delete(axis=0):\n", arr_deleted_axis0)

Dizi arr: [1 2 3]
np.append(arr, [4, 5]): [1 2 3 4 5]

np.append(axis=0):
 [[1 2]
 [3 4]
 [5 6]]

np.append(axis=1):
 [[1 2 7]
 [3 4 8]]

np.insert(arr, 1, 99): [ 1 99  2  3]
np.insert(arr, [1, 3], [88, 77]): [ 1 88  2  3 77]

np.delete(arr_appended, [0, 2]): [2 4 5]

np.delete(axis=0):
 [[1 2]
 [5 6]]


## 12. Dizileri Birleştirme ve Bölme

### 12.1. Birleştirme (`concatenate`, `vstack`, `hstack`)
- **`np.concatenate((arr1, arr2, ...), axis=0)`**: Dizileri belirtilen eksen boyunca birleştirir. Boyutlar diğer eksenlerde aynı olmalıdır.
- **`np.vstack((arr1, arr2, ...))`**: Dizileri dikey olarak (üst üste) birleştirir (`concatenate`'in `axis=0` hali).
- **`np.hstack((arr1, arr2, ...))`**: Dizileri yatay olarak (yan yana) birleştirir (`concatenate`'in `axis=1` hali).

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print("arr1:\n", arr1)
print("arr2:\n", arr2)

# concatenate
arr_cat_axis0 = np.concatenate((arr1, arr2), axis=0)
print("\nnp.concatenate (axis=0):\n", arr_cat_axis0)
arr_cat_axis1 = np.concatenate((arr1, arr2), axis=1)
print("\nnp.concatenate (axis=1):\n", arr_cat_axis1)

# vstack (vertical stack)
arr_vstack = np.vstack((arr1, arr2))
print("\nnp.vstack:\n", arr_vstack)

# hstack (horizontal stack)
arr_hstack = np.hstack((arr1, arr2))
print("\nnp.hstack:\n", arr_hstack)

arr1:
 [[1 2]
 [3 4]]
arr2:
 [[5 6]
 [7 8]]

np.concatenate (axis=0):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

np.concatenate (axis=1):
 [[1 2 5 6]
 [3 4 7 8]]

np.vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

np.hstack:
 [[1 2 5 6]
 [3 4 7 8]]


### 12.2. Bölme (`split`, `vsplit`, `hsplit`)
- **`np.split(arr, indices_or_sections, axis=0)`**: Diziyi belirtilen eksen boyunca böler.
  - `indices_or_sections` bir tamsayı (`N`) ise, dizi `N` eşit parçaya bölünür (bölünebiliyorsa).
  - `indices_or_sections` bir liste veya dizi ise, belirtilen indekslerden *önce* bölme yapılır.
- **`np.vsplit(arr, indices_or_sections)`**: Diziyi dikey olarak böler (`split`'in `axis=0` hali).
- **`np.hsplit(arr, indices_or_sections)`**: Diziyi yatay olarak böler (`split`'in `axis=1` hali).

In [ ]:
arr = np.arange(16).reshape((4, 4))
print("Dizi arr:\n", arr)

# split (eşit parçalara)
arr_split_axis0 = np.split(arr, 2, axis=0) # Dikey olarak 2 eşit parçaya böl
print("\nnp.split(axis=0, sections=2):")
print("Parça 1:\n", arr_split_axis0[0])
print("Parça 2:\n", arr_split_axis0[1])

arr_split_axis1 = np.split(arr, 2, axis=1) # Yatay olarak 2 eşit parçaya böl
print("\nnp.split(axis=1, sections=2):")
print("Parça 1:\n", arr_split_axis1[0])
print("Parça 2:\n", arr_split_axis1[1])

# split (indekslere göre)
# 1. indeksten önce ve 3. indeksten önce dikey böl
arr_split_indices = np.split(arr, [1, 3], axis=0)
print("\nnp.split(axis=0, indices=[1, 3]):")
print("Parça 1 (satır 0):\n", arr_split_indices[0])
print("Parça 2 (satır 1, 2):\n", arr_split_indices[1])
print("Parça 3 (satır 3):\n", arr_split_indices[2])

# vsplit ve hsplit
arr_vsplit = np.vsplit(arr, 2) # np.split(arr, 2, axis=0) ile aynı
print("\nnp.vsplit(sections=2):")
print("Parça 1:\n", arr_vsplit[0])
print("Parça 2:\n", arr_vsplit[1])

arr_hsplit = np.hsplit(arr, [1, 3]) # np.split(arr, [1, 3], axis=1) ile aynı
print("\nnp.hsplit(indices=[1, 3]):")
print("Parça 1 (sütun 0):\n", arr_hsplit[0])
print("Parça 2 (sütun 1, 2):\n", arr_hsplit[1])
print("Parça 3 (sütun 3):\n", arr_hsplit[2])

Dizi arr:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

np.split(axis=0, sections=2):
Parça 1:
 [[0 1 2 3]
 [4 5 6 7]]
Parça 2:
 [[ 8  9 10 11]
 [12 13 14 15]]

np.split(axis=1, sections=2):
Parça 1:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Parça 2:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]

np.split(axis=0, indices=[1, 3]):
Parça 1 (satır 0):
 [[0 1 2 3]]
Parça 2 (satır 1, 2):
 [[ 4  5  6  7]
 [ 8  9 10 11]]
Parça 3 (satır 3):
 [[12 13 14 15]]

np.vsplit(sections=2):
Parça 1:
 [[0 1 2 3]
 [4 5 6 7]]
Parça 2:
 [[ 8  9 10 11]
 [12 13 14 15]]

np.hsplit(indices=[1, 3]):
Parça 1 (sütun 0):
 [[ 0]
 [ 4]
 [ 8]
 [12]]
Parça 2 (sütun 1, 2):
 [[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
Parça 3 (sütun 3):
 [[ 3]
 [ 7]
 [11]
 [15]]


## 13. Küme İşlemleri (Set Operations)

- Genellikle tek boyutlu diziler üzerinde çalışır ve matematiksel küme işlemlerini gerçekleştirir.
- **`np.unique(arr)`**: Dizideki benzersiz elemanları sıralı olarak döndürür.
  - `return_counts=True`: Her elemanın kaç kez geçtiğini de döndürür.
- **`np.intersect1d(arr1, arr2)`**: İki dizinin kesişimini (ortak elemanlar).
- **`np.union1d(arr1, arr2)`**: İki dizinin birleşimini (tüm benzersiz elemanlar).
- **`np.in1d(arr1, arr2)`**: `arr1`'in her elemanının `arr2`'de olup olmadığını kontrol eden boolean dizi.
- **`np.setdiff1d(arr1, arr2)`**: `arr1`'de olup `arr2`'de *olmayan* elemanlar (fark).
- **`np.setxor1d(arr1, arr2)`**: Sadece bir dizide bulunan (her ikisinde birden olmayan) elemanlar (simetrik fark).

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5, 5, 3])
arr2 = np.array([3, 4, 5, 6, 7])
print("arr1:", arr1)
print("arr2:", arr2)

# unique
unique_arr1, counts = np.unique(arr1, return_counts=True)
print("\nnp.unique(arr1):", unique_arr1)
print("Tekrar Sayıları:", counts)

# intersect1d
intersection = np.intersect1d(arr1, arr2)
print("\nKesişim (np.intersect1d):", intersection)

# union1d
union = np.union1d(arr1, arr2)
print("\nBirleşim (np.union1d):", union)

# in1d
is_in = np.in1d(arr1, arr2)
print("\narr1 elemanları arr2'de var mı? (np.in1d):", is_in)

# setdiff1d
diff1 = np.setdiff1d(arr1, arr2) # arr1'de olup arr2'de olmayanlar
print("\nFark (np.setdiff1d(arr1, arr2)):", diff1)
diff2 = np.setdiff1d(arr2, arr1) # arr2'de olup arr1'de olmayanlar
print("Fark (np.setdiff1d(arr2, arr1)):", diff2)

# setxor1d
xor = np.setxor1d(arr1, arr2) # Sadece birinde olanlar
print("\nSimetrik Fark (np.setxor1d):", xor)

arr1: [1 2 3 4 5 5 3]
arr2: [3 4 5 6 7]

np.unique(arr1): [1 2 3 4 5]
Tekrar Sayıları: [1 1 2 1 2]

Kesişim (np.intersect1d): [3 4 5]

Birleşim (np.union1d): [1 2 3 4 5 6 7]

arr1 elemanları arr2'de var mı? (np.in1d): [False False  True  True  True  True  True]

Fark (np.setdiff1d(arr1, arr2)): [1 2]
Fark (np.setdiff1d(arr2, arr1)): [6 7]

Simetrik Fark (np.setxor1d): [1 2 6 7]


<ipython-input-37-87f8e85b86ff>:20: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  is_in = np.in1d(arr1, arr2)


## 14. Lineer Cebir (`np.linalg`)

- NumPy'ın lineer cebir işlemleri için alt modülüdür.
- **Matris Çarpımı**:
  - `np.dot(a, b)` veya `a.dot(b)` veya `a @ b`.
  - Dikkat: `a * b` eleman bazında çarpımdır.
- **Determinant**: `np.linalg.det(a)`.
- **İz (Trace)**: `np.trace(a)` (Köşegen toplamı - `linalg` içinde değil!).
- **Ters Matris (Inverse)**: `np.linalg.inv(a)` (Sadece kare ve tekil olmayan matrisler için).
- **Sözde Ters Matris (Pseudo-inverse)**: `np.linalg.pinv(a)` (Kare olmayan veya tekil matrisler için).
- **Lineer Denklem Sistemi Çözümü ($Ax = b$)**:
  - `np.linalg.solve(A, b)`: Tam çözüm (A kare ve tersi alınabilir olmalı).
  - `np.linalg.lstsq(A, b, rcond=None)`: En küçük kareler çözümü.
- **Özdeğerler ve Özvektörler**:
  - `np.linalg.eigvals(a)`: Sadece özdeğerler.
  - `w, v = np.linalg.eig(a)`: `w` özdeğerleri, `v` özvektörleri (sütunlarda).
- **Tekil Değer Ayrıştırması (SVD)**: `u, s, v = np.linalg.svd(a)`.
- **QR Ayrıştırması**: `q, r = np.linalg.qr(a)`.

In [ ]:
# Lineer Cebir Örnekleri
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
b_vec = np.array([1, 2])

print("Matris A:\n", A)
print("Matris B:\n", B)
print("Vektör b:", b_vec)

# Matris Çarpımı
mat_mul = A @ B
print("\nMatris Çarpımı (A @ B):\n", mat_mul)

# Determinant
det_A = np.linalg.det(A)
print("\nDeterminant (det(A)):", det_A)

# İz (Trace)
trace_A = np.trace(A)
print("\nİz (trace(A)):", trace_A)

# Ters Matris
try:
    inv_A = np.linalg.inv(A)
    print("\nTers Matris (inv(A)):\n", inv_A)
    # Doğrulama: A @ inv(A) birim matris olmalı (yaklaşık olarak)
    print("\nDoğrulama (A @ inv(A)):\n", np.round(A @ inv_A))
except np.linalg.LinAlgError:
    print("\nMatrisin tersi alınamıyor (tekil matris)." )

# Lineer Denklem Çözümü (Ax = b_vec)
try:
    x_sol = np.linalg.solve(A, b_vec)
    print("\nDenklem Çözümü (solve(A, b_vec)):", x_sol)
    # Doğrulama: A @ x_sol, b_vec'e eşit olmalı
    print("\nDoğrulama (A @ x_sol):", A @ x_sol)
except np.linalg.LinAlgError:
        print("\nDenklem sistemi çözülemiyor.")

# Özdeğerler ve Özvektörler
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nÖzdeğerler (eigvals):", eigenvalues)
print("Özvektörler (eigvecs):\n", eigenvectors)

# SVD
U, s, V_T = np.linalg.svd(A)
print("\nSVD U:\n", U)
print("SVD s (tekil değerler):", s)
print("SVD V^T:\n", V_T)

Matris A:
 [[1 2]
 [3 4]]
Matris B:
 [[5 6]
 [7 8]]
Vektör b: [1 2]

Matris Çarpımı (A @ B):
 [[19 22]
 [43 50]]

Determinant (det(A)): -2.0000000000000004

İz (trace(A)): 5

Ters Matris (inv(A)):
 [[-2.   1. ]
 [ 1.5 -0.5]]

Doğrulama (A @ inv(A)):
 [[1. 0.]
 [0. 1.]]

Denklem Çözümü (solve(A, b_vec)): [0.  0.5]

Doğrulama (A @ x_sol): [1. 2.]

Özdeğerler (eigvals): [-0.37228132  5.37228132]
Özvektörler (eigvecs):
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

SVD U:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
SVD s (tekil değerler): [5.4649857  0.36596619]
SVD V^T:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


# Çalışma Sonu
